### ISSUE TITLE
uSync Support in Chauffeur

### ISSUE THREAD

**Issue by KevinJump** [aaronpowell/Chauffeur.uSync#2]
Hello,

Now that uSync 3 might actually be something described as stable(ish), I have been thinking about the command line stuff. Are you doing any active work on this project? 

with v3 some of this would be way simpler (for example the core api, now takes and spits out the XML without going to disk) - I am happy to have a go at this, although to be honest it probably won't be in F# but i don't want to do anything you have already got in progress.

Kevin

**Comment by aaronpowell** [comment]
At present I haven't been looking at this (the project that it was for dropped off so it become a lower priority).

I'm happy to have a C# version if you want to look into it, I can add you as a collaborator on this repo if you want (and override the code I've got thus far) to have the name, or have it under the usync stack.

**Comment by KevinJump** [comment]
Cool, I am going to do it under usync for now, not least it makes it easier to keep in sync with any changes etc that i will probably make to get it working :)
